// Auto-generated by: npx supabase gen types typescript --project-id <id> > src/lib/database.types.ts
// Re-run after any schema change. This stub is replaced once Supabase is provisioned (Task 0.2).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      tournaments: {
        Row: {
          id: string
          name: string
          slug: string
          start_date: string
          end_date: string
          venue_name: string
          venue_address: string
          city: string
          state: string
          hero_image_url: string | null
          description_md: string | null
          status: 'draft' | 'published' | 'closed' | 'completed' | 'cancelled'
          registration_opens_at: string | null
          registration_closes_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['tournaments']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['tournaments']['Insert']>
      }
      tournament_days: {
        Row: {
          id: string
          tournament_id: string
          day_date: string
          label: string
          schedule_md: string | null
          check_in_time: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['tournament_days']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['tournament_days']['Insert']>
      }
      divisions: {
        Row: {
          id: string
          tournament_day_id: string
          skill_level: string
          gender: 'mens' | 'womens' | 'coed' | 'boys' | 'girls'
          display_name: string
          format: 'doubles' | 'triples' | 'quads' | 'sixes'
          fee_cents: number
          min_roster: number
          max_roster: number
          max_teams: number | null
          status: 'open' | 'waitlist' | 'closed'
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['divisions']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['divisions']['Insert']>
      }
      teams: {
        Row: {
          id: string
          division_id: string
          team_name: string
          city: string
          captain_name: string
          captain_email: string
          captain_phone: string
          status: 'pending_payment' | 'confirmed' | 'waitlisted' | 'cancelled'
          management_token: string
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['teams']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['teams']['Insert']>
      }
      players: {
        Row: {
          id: string
          team_id: string
          name: string
          jersey_number: number | null
          shirt_size: string | null
          sort_order: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['players']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['players']['Insert']>
      }
      registration_orders: {
        Row: {
          id: string
          captain_email: string
          total_cents: number
          stripe_checkout_session_id: string | null
          status: 'pending' | 'paid' | 'failed' | 'refunded'
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['registration_orders']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['registration_orders']['Insert']>
      }
      registrations: {
        Row: {
          id: string
          order_id: string
          team_id: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['registrations']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['registrations']['Insert']>
      }
      payments: {
        Row: {
          id: string
          order_id: string
          amount_cents: number
          currency: string
          stripe_payment_intent_id: string
          stripe_charge_id: string | null
          refunded_amount_cents: number
          refunded_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['payments']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['payments']['Insert']>
      }
      processed_webhooks: {
        Row: {
          event_id: string
          processed_at: string
        }
        Insert: Database['public']['Tables']['processed_webhooks']['Row']
        Update: Partial<Database['public']['Tables']['processed_webhooks']['Insert']>
      }
    }
    Views: {
      teams_public: {
        Row: {
          id: string
          division_id: string
          team_name: string
          city: string
          captain_name: string
          status: string
        }
      }
    }
    Functions: {
      manage_team_lookup: {
        Args: { token: string }
        Returns: Json
      }
      manage_team_update_player: {
        Args: { p_token: string; p_player_id: string; p_name: string; p_shirt_size: string | null; p_jersey_number: number | null }
        Returns: boolean
      }
    }
    Enums: Record<string, never>
  }
}
